tasks_cfgs:
  nut_assembly:
    name: nut_assembly
    n_tasks: 9
    crop:
    - 20
    - 25
    - 80
    - 75
    n_per_task: 3
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    loss_mul: 1
    task_per_batch: 9
    traj_per_subtask: 100
    demo_per_subtask: 100
  door:
    name: door
    n_tasks: 4
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 8
    task_ids:
    - 0
    - 1
    - 2
    - 3
    loss_mul: 1
    task_per_batch: 4
    traj_per_subtask: 100
    demo_per_subtask: 100
  drawer:
    name: drawer
    n_tasks: 8
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 3
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    loss_mul: 1
    task_per_batch: 8
    traj_per_subtask: 100
    demo_per_subtask: 100
  button:
    name: button
    n_tasks: 6
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 5
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    loss_mul: 1
    task_per_batch: 6
    traj_per_subtask: 100
    demo_per_subtask: 100
  pick_place:
    name: pick_place
    n_tasks: 16
    demo_crop:
    - 20
    - 25
    - 80
    - 75
    agent_crop:
    - 0
    - 30
    - 120
    - 120
    agent_sim_crop:
    - 20
    - 25
    - 80
    - 75
    n_per_task: 2
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    skip_ids: []
    loss_mul: 1
    task_per_batch: 16
    traj_per_subtask: 40
    demo_per_subtask: 100
  stack_block:
    name: stack_block
    n_tasks: 6
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 5
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    loss_mul: 1
    task_per_batch: 6
    traj_per_subtask: 100
    demo_per_subtask: 100
  basketball:
    name: basketball
    n_tasks: 12
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 3
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    loss_mul: 1
    task_per_batch: 12
    traj_per_subtask: 100
    demo_per_subtask: 100
debug: false
EXPERT_DATA: /home/rsofnc000/dataset/opt_dataset
save_path: /home/rsofnc000/checkpoint_save_folder
wandb_log: true
project_name: Real-1Task-pick_place-CTOD-Finetune
log_freq: 20
val_freq: -1
print_freq: 20
save_freq: -1
cosine_annealing: false
save_optim: true
resume: false
finetune: true
resume_path: /home/rsofnc000/checkpoint_save_folder/1Task-Pick-Place-Cond-Target-Obj-Detector-separate-demo-agent-Batch80
resume_step: 64152
device: 0
exp_name: Real-1Task-pick_place-CTOD-Finetune-Batch112
epochs: 90
bsize: 112
vsize: 112
optimizer: AdamW
task_names: pick_place
dataset_target: multi_task_il.datasets.multi_task_cond_target_obj_dataset.CondTargetObjDetectorDataset
inv_mul: 0
bc_mul: 0
ce_mul: 0
pnt_mul: 0
rep_muls:
  img_byol: ${byol.mul_pre}
  attn_byol: ${byol.mul_pos}
  demo_byol: ${byol.mul_demo}
  intm_byol: ${byol.mul_intm}
  simclr_pre: ${simclr.mul_pre}
  simclr_post: ${simclr.mul_pos}
  simclr_intm: ${simclr.mul_intm}
rollout: false
train_cfg:
  batch_size: ${bsize}
  val_size: ${vsize}
  lr: 1.0e-05
  optimizer: ${optimizer}
  epochs: ${epochs}
  log_freq: ${log_freq}
  save_freq: ${save_freq}
  print_freq: ${print_freq}
  val_freq: ${val_freq}
  inv_loss_mult: ${inv_mul}
  bc_loss_mult: ${bc_mul}
  pnt_loss_mult: ${pnt_mul}
  rep_loss_muls: ${rep_muls}
  dataset: ${dataset_cfg}
  sampler: ${samplers}
  target_update_freq: 5
  early_stopping: ${early_stopping_cfg}
  weight_decay: 5
  lr_schedule: ReduceLROnPlateau
early_stopping_cfg:
  patience: 20
  delta: 0.001
tasks:
- name: pick_place
  n_tasks: 16
  demo_crop:
  - 20
  - 25
  - 80
  - 75
  agent_crop:
  - 0
  - 30
  - 120
  - 120
  agent_sim_crop:
  - 20
  - 25
  - 80
  - 75
  n_per_task: 7
  task_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  skip_ids: []
  loss_mul: 1
  task_per_batch: 16
  traj_per_subtask: 40
  demo_per_subtask: 100
single_task: false
exclude_task: false
use_all_tasks: false
set_same_n: 7
limit_num_traj: -1
limit_num_demo: -1
loader_workers: 8
samplers:
  batch_size: ${bsize}
  drop_last: false
  shuffle: true
  balancing_policy: 0
val_skip: true
train_skip: true
dataset_cfg:
  _target_: ${dataset_target}
  root_dir: ${EXPERT_DATA}
  mode: ???
  tasks_spec: ${tasks}
  aux_pose: false
  height: 100
  width: 180
  split:
  - 0.9
  - 0.1
  dagger: false
  demo_T: 4
  obs_T: 7
  data_augs: ${augs}
  non_sequential: true
  aug_twice: false
  allow_val_skip: ${val_skip}
  allow_train_skip: ${train_skip}
  use_strong_augs: false
  select_random_frames: true
  compute_obj_distribution: false
  agent_name: real_new_ur5e
  demo_name: panda
  load_action: false
  load_state: false
  state_spec:
  - action
  action_spec: action
  normalize_action: true
  normalization_ranges:
  - - -0.35
    - 0.35
  - - -0.35
    - 0.35
  - - 0.6
    - 1.2
  - - -3.14
    - 3.14911766
  - - -3.14911766
    - 3.14911766
  - - -3.14911766
    - 3.14911766
  n_action_bin: 256
  first_frames: false
  only_first_frame: false
  task_id: false
  tasks: {}
  n_tasks: 16
  perform_augs: true
  perform_scale_resize: true
  change_command_epoch: false
  load_eef_point: false
  mix_sim_real: false
augs:
  old_aug: false
  brightness:
  - 0.875
  - 1.125
  contrast:
  - 0.5
  - 1.5
  saturation:
  - 0.5
  - 1.5
  hue:
  - -0.05
  - 0.05
  p: 1.0
  horizontal_flip_p: 0.1
  affine: false
  brightness_strong:
  - 0.875
  - 1.125
  contrast_strong:
  - 0.5
  - 1.5
  saturation_strong:
  - 0.5
  - 1.5
  hue_strong:
  - -0.05
  - 0.05
  p_strong: 0.5
  horizontal_flip_p_strong: 0.5
policy: ${cond_target_obj_detector}
cond_target_obj_detector:
  _target_: multi_task_il.models.cond_target_obj_detector.cond_target_obj_detector.CondTargetObjectDetector
  cond_target_obj_detector_cfg: ${cond_target_obj_detector_cfg}
cond_target_obj_detector_cfg:
  height: 100
  width: 180
  demo_T: 4
  obs_T: 7
  cond_backbone_name: r2plus1d_18
  agent_backbone_name: resnet18
  cond_video: true
  pretrained: false
  anc_scales:
  - 1.0
  - 1.5
  - 2.0
  - 3.0
  - 4.0
  anc_ratios:
  - 0.2
  - 0.5
  - 0.8
  - 1
  - 1.2
  - 1.5
  - 2.0
  dim_H: 13
  dim_W: 23
  n_channels: 128
  conv_drop_dim: 4
  gpu_id: 0
  demo_ff_dim:
  - 128
  - 64
  - 32
  demo_linear_dim:
  - 256
  - 128
  task_embedding_dim: 128
  n_classes: 2
actions:
  adim: 7
  sdim: 7
  action_cfg: 6
  n_mixtures: 7
  const_var: false
  sep_var: true
cond_policy:
  _target_: multi_task_il.models.cond_target_obj_detector.policy.CondPolicy
  cond_target_obj_detector_pretrained: true
  cond_target_obj_detector_weights: /user/frosa/multi_task_lfd/Multi-Task-LFD-Framework/mosaic-baseline-sav-folder/TARGET_OBJ_DETECTOR_SLOT/1Task-Pick-Place-Cond-Target-Obj-Detector-Batch32/
  cond_target_obj_detector_step: 4050
  action_cfg: ${actions}
  freeze_target_detector: true
  concat_state: true
  concat_bb: true
  mlp_layers:
  - 1024
  - 512
  - 256
  spatial_softmax: false
  gt_bb: false
  n_tasks:
  - 16
  min_std:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
