tasks_cfgs:
  nut_assembly:
    name: nut_assembly
    n_tasks: 9
    crop:
    - 20
    - 25
    - 80
    - 75
    n_per_task: 3
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    loss_mul: 1
    task_per_batch: 9
    traj_per_subtask: 100
    demo_per_subtask: 100
  door:
    name: door
    n_tasks: 4
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 8
    task_ids:
    - 0
    - 1
    - 2
    - 3
    loss_mul: 1
    task_per_batch: 4
    traj_per_subtask: 100
    demo_per_subtask: 100
  drawer:
    name: drawer
    n_tasks: 8
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 3
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    loss_mul: 1
    task_per_batch: 8
    traj_per_subtask: 100
    demo_per_subtask: 100
  button:
    name: button
    n_tasks: 6
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 5
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    loss_mul: 1
    task_per_batch: 6
    traj_per_subtask: 100
    demo_per_subtask: 100
  pick_place:
    name: pick_place
    n_tasks: 16
    demo_crop:
    - 20
    - 25
    - 80
    - 75
    agent_crop:
    - 0
    - 30
    - 120
    - 120
    agent_sim_crop:
    - 20
    - 25
    - 80
    - 75
    n_per_task: 2
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    skip_ids: []
    loss_mul: 1
    task_per_batch: 16
    traj_per_subtask: 40
    demo_per_subtask: 100
  stack_block:
    name: stack_block
    n_tasks: 6
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 5
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    loss_mul: 1
    task_per_batch: 6
    traj_per_subtask: 100
    demo_per_subtask: 100
  basketball:
    name: basketball
    n_tasks: 12
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 3
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    loss_mul: 1
    task_per_batch: 12
    traj_per_subtask: 100
    demo_per_subtask: 100
debug: false
EXPERT_DATA: /home/rsofnc000/dataset/opt_dataset/
save_path: /home/rsofnc000/checkpoint_save_folder
wandb_log: true
project_name: Real-Pick-Place-MOSAIC-CTOD-No-State-Finetune
log_freq: 10
val_freq: -1
print_freq: 1
save_freq: -1
cosine_annealing: false
save_optim: true
resume: false
finetune: true
resume_path: 1Task-pick_place-MOSAIC-CTOD-State-false-ZERO_BB_AFTER_PICK_Convertion_true-Batch32
resume_step: 288630
device: 0
exp_name: Real-Pick-Place-MOSAIC-CTOD-No-State-Finetune-Batch48
epochs: 90
bsize: 48
vsize: 48
optimizer: AdamW
task_names: pick_place
rollout: false
dataset_target: multi_task_il.datasets.multi_task_datasets.MultiTaskPairedDataset
inv_mul: 0.0
bc_mul: 1.0
ce_mul: 0
pnt_mul: 0
rep_muls:
  img_byol: ${byol.mul_pre}
  attn_byol: ${byol.mul_pos}
  demo_byol: ${byol.mul_demo}
  intm_byol: ${byol.mul_intm}
  simclr_pre: ${simclr.mul_pre}
  simclr_post: ${simclr.mul_pos}
  simclr_intm: ${simclr.mul_intm}
train_cfg:
  batch_size: ${bsize}
  val_size: ${vsize}
  lr: 0.0005
  optimizer: ${optimizer}
  epochs: ${epochs}
  log_freq: ${log_freq}
  save_freq: ${save_freq}
  print_freq: ${print_freq}
  val_freq: ${val_freq}
  inv_loss_mult: ${inv_mul}
  bc_loss_mult: ${bc_mul}
  pnt_loss_mult: ${pnt_mul}
  rep_loss_muls: ${rep_muls}
  dataset: ${dataset_cfg}
  sampler: ${samplers}
  target_update_freq: 5
  early_stopping: ${early_stopping_cfg}
  weight_decay: 0.0
  lr_schedule: None
early_stopping_cfg:
  patience: -1
  delta: 0.001
tasks:
- name: pick_place
  n_tasks: 16
  demo_crop:
  - 20
  - 25
  - 80
  - 75
  agent_crop:
  - 0
  - 30
  - 120
  - 120
  agent_sim_crop:
  - 20
  - 25
  - 80
  - 75
  n_per_task: 3
  task_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  skip_ids: []
  loss_mul: 1
  task_per_batch: 16
  traj_per_subtask: 40
  demo_per_subtask: 100
single_task: false
exclude_task: false
use_all_tasks: false
set_same_n: 3
limit_num_traj: -1
limit_num_demo: -1
loader_workers: 16
samplers:
  batch_size: ${bsize}
  drop_last: false
  shuffle: true
  balancing_policy: 0
val_skip: true
train_skip: true
dataset_cfg:
  _target_: ${dataset_target}
  root_dir: ${EXPERT_DATA}
  mode: ???
  tasks_spec: ${tasks}
  aux_pose: false
  height: 100
  width: 180
  split:
  - 1.0
  - 0.0
  demo_T: 4
  obs_T: 7
  normalize_action: true
  pick_next: true
  load_bb: true
  dagger: false
  normalization_ranges:
  - - -0.4
    - 0.4
  - - 0.1
    - 0.9
  - - -0.2
    - 0.2
  - - -3.14911766
    - 3.14911766
  - - -3.14911766
    - 3.14911766
  - - -3.14911766
    - 3.14911766
  n_action_bin: 256
  take_first_frame: ${policy.concat_target_obj_embedding}
  data_augs: ${augs}
  non_sequential: false
  crop_twice: true
  state_spec:
  - joint_pos
  - gripper_state
  allow_val_skip: ${val_skip}
  allow_train_skip: ${train_skip}
  use_strong_augs: true
  select_random_frames: true
  compute_obj_distribution: false
  agent_name: real_new_ur5e
  demo_name: panda
  perform_augs: true
  perform_scale_resize: true
  change_command_epoch: true
  load_eef_point: false
  split_pick_place: false
augs:
  old_aug: false
  brightness:
  - 0.9
  - 1.1
  contrast:
  - 0.9
  - 1.1
  saturation:
  - 0.9
  - 1.1
  hue:
  - 0.0
  - 0.0
  p: 0.1
  horizontal_flip_p: 0.1
  brightness_strong:
  - 0.875
  - 1.125
  contrast_strong:
  - 0.5
  - 1.5
  saturation_strong:
  - 0.5
  - 1.5
  hue_strong:
  - -0.05
  - 0.05
  p_strong: 0.5
  horizontal_flip_p_strong: 0.5
  null_bb: false
simclr:
  demo_T: 4
  obs_T: 7
  mul_pre: 0.0
  mul_pos: 0.0
  mul_intm: 0
  tau: 0.005
  compressor_dim: 256
  temporal: true
  hidden_dim: 512
  fix_step: -1
byol:
  p: 2
  project_dim: 128
  hidden_dim: 256
  demo_T: 4
  obs_T: 7
  demo_proj: true
  share_mlp: true
  no_hidden: false
  draw_apart: false
  mul_pre: 0
  mul_pos: 0
  mul_intm: 0
  mul_demo: 0
policy: ${mosaic}
mosaic:
  _target_: multi_task_il.models.mt_rep.VideoImitation
  load_target_obj_detector: true
  target_obj_detector_step: 38880
  target_obj_detector_path: /home/gianl/catkin_ws/src/Ur5e-2f-85f/ur5e_2f_85_controller/src/ai_controller/checkpoint/ctod/Real-1Task-pick_place-CTOD-Finetune-Batch112
  freeze_target_obj_detector: false
  remove_class_layers: false
  load_contrastive: false
  load_inv: true
  concat_target_obj_embedding: false
  latent_dim: 40
  sdim: 7
  concat_state: false
  concat_bb: true
  height: ${train_cfg.dataset.height}
  width: ${train_cfg.dataset.width}
  demo_T: ${train_cfg.dataset.demo_T}
  obs_T: ${train_cfg.dataset.obs_T}
  dim_H: 13
  dim_W: 23
  demo_mean: true
  action_cfg: ${actions}
  concat_demo_head: false
  concat_demo_act: true
  attn_cfg: ${attn}
  byol_config: ${byol}
  simclr_config: ${simclr}
actions:
  n_layers: 2
  out_dim: 128
  hidden_dim: 128
  adim: 7
  n_mixtures: 3
  const_var: false
  sep_var: true
  concat_demo_head: false
  concat_demo_act: true
  concat_img_emb: true
  concat_demo_emb: true
  demo_mean: true
attn:
  embed_hidden: 256
  dropout: 0.2
  n_attn_layers: 2
  attn_heads: 4
  attn_ff: 256
  pos_enc: true
  fuse_starts: 0
  causal: true
  attend_demo: true
  demo_out: true
  max_len: 5000
  img_cfg:
    network_flag: 0
    out_feature: 128
    drop_dim: 4
    pretrained: false
tosil:
  _target_: multi_task_il.models.baselines.InverseImitation
  latent_dim: 40
  lstm_config:
    out_dim: 32
    n_layers: 1
    is_rnn: false
  vis:
    conv_drop_dim: 2
    st_goal_attn: true
    n_st_attn: 2
    use_pe: true
    attn_heads: 4
  const_var: true
  sdim: 9
  adim: 8
  n_mixtures: 2
  concat_state: false
  pred_point: true
  concat_target_obj_embedding: false
  load_target_obj_detector: false
  freeze_target_obj_detector: false
  target_obj_detector_step: 0
  target_obj_detector_path: null
  transformer_feat: true
lstm:
  _target_: multi_task_il.models.baselines.InverseImitation
  latent_dim: 40
  lstm_config:
    out_dim: 32
    n_layers: 1
    is_rnn: false
  vis:
    temp_convs: false
    lstm: true
    out_feature: 256
    context_T: 4
  n_mixtures: 2
  const_var: true
  concat_state: false
  pred_point: true
  transformer_feat: false
use_daml: false
daml:
  _target_: multi_task_il.models.baselines.DAMLNetwork
  n_final_convs: resnet
  T_context: 4
  maml_lr: 0.1
  first_order: false
  adim: 8
  n_mix: 2
  const_var: true
  concat_target_obj_embedding: false
vima:
  _target_: multi_task_il.models.vima.policy.Policy
  embed_dim: 640
  xf_n_layers: 7
  sattn_n_heads: 20
  xattn_n_heads: 20
  views:
  - front
  return_dist: true
  concat_state: true
  ckpt_path: /home/frosa_loc/Multi-Task-LFD-Framework/repo/Multi-Task-LFD-Training-Framework/training/multi_task_il/models/vima/ckpt/92M.ckpt
